#!/usr/bin/perl

$ws3 = "http://localhost:8080/skim/weather/summary";

sub fakencode {
   $_ = shift;
   s/,/%2C/g;
   s/ /\+/g;
   return $_;
}

if (@ARGV < 1) {
   print "expected zipcode or city, state\n";
   exit 1;
}

$str = fakencode(join(' ',@ARGV));
# use a wget call to lookup the lat/lon coordinates
$url = "http://forecast.weather.gov/zipcity.php?inputstring=$str";
$_ = `wget --max-redirect=0 '$url' 2>&1`;

# change the redirect-url to get the xml version of the data
if (/Location: (.*?) /) {
   $url = $1."&unit=0&lg=english&FcstType=dwml";
} else {
   print $_;
   die "brittle code";
}

$t = sprintf("/tmp/.skim%x", int(rand(99999))); #good enough
system("curl", "-s", "-o", $t, $url);
system("curl", "-X", "POST", "--header", "Content-Type: application/xml",
     "--data-binary", '@'.$t, $ws3);
unlink $t;
